name: Build Android AAB with Expo
on: push


jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18.x' # Specify your Node.js version
        - run: npm install # or yarn install
        - run: npm install -g expo-cli
        - run: expo login -u ${{ 'sportlystapp' }} -p ${{ 'sportlystapp@1123' }}
        - run: eas build -p android